### PR TITLE
Section3 ABOUT page

### PR DESCRIPTION
**Pull request by TatsianaRud**

### CODE REVIEW

**Review by bringmetheaxx — CHANGES_REQUESTED** [review]
Can you check the conflicts please?

**Comment by TatsianaRud** [comment]
yep i ll do

**Comment by TatsianaRud** [comment]
Conflict fixed

**Comment by danielhalasz** [comment]
perfect Tatsiana, thanks

**Review by danielhalasz — APPROVED** [review]
LGTM

**Review by bringmetheaxx — APPROVED** [review]
great!

**Pull request merged**
