### PR TITLE
image folder added

### PR DESCRIPTION
**Pull request by Senait-coding**
Some image and image folder added

### CODE REVIEW

**Comment by danielhalasz** [comment]
hi @Senait-coding what are these screenshots for?

**Comment by danielhalasz** [comment]
ok, I realized reviewing another PR that these are linked to in the readme.md... if it would be mentioned in the PR here, would be easier to understand for me :)

**Review by danielhalasz — APPROVED** [review]
yeah

**Review by bringmetheaxx — APPROVED** [review]
all is ok

**Pull request merged**
