### PR TITLE
 program apply box and program box img.added

### PR DESCRIPTION
**Pull request by Senait-coding**

### CODE REVIEW

**Comment by danielhalasz** [comment]
@Senait-coding it has some conflicts

**Comment by Senait-coding** [comment]
> @Senait-coding it has some conflicts

@danielhalasz yes,  resolved now . thanks

**Review by danielhalasz — APPROVED** [review]
looks good

**Review by TatsianaRud — APPROVED** [review]

**Comment by TatsianaRud** [comment]
looks good)

**Pull request merged**
