### PR TITLE
Section 6

### PR DESCRIPTION
**Pull request by TatsianaRud**
i see there is conflicts but i dont know what here i shoud leave.

### CODE REVIEW

**Comment by danielhalasz** [comment]
@TatsianaRud try to: 

> git fetch origin 

> git checkout -b section-6 origin/section-6

> git merge main

then try to make sure that everything stays from others' code and also your new stuff :)

**Comment by bringmetheaxx** [comment]
@TatsianaRud can you resolve the conflicts here please?

**Comment by TatsianaRud** [comment]
i resolved conflict,can u check?Everything is working ok only 1sect for Moamin strange

**Review by bringmetheaxx — APPROVED** [review]
goooood

**Review by Senait-coding — APPROVED** [review]
checked ,perfect! only Moamin's part needs some amendement

**Pull request merged**
