### PR TITLE
try to update everything

### PR DESCRIPTION
**Pull request by Moamin-AbuEwaida**
Check this out guys
@Senait-coding @danielhalasz

### CODE REVIEW

**Comment by danielhalasz** [comment]
@Moamin-AbuEwaida it has conflicts

**Comment by Senait-coding** [comment]
@Moamin-AbuEwaida I  fix the conflict but I noted the fonts you used and the size of the img. is not according to the original website  , you do it purposely? me, just copied it from the original website  :)

**Comment by Moamin-AbuEwaida** [comment]
> @Moamin-AbuEwaida I have fixed the conflict but I noted the fonts you used and the size of the img. is not according to the original website , you do it purposely? me, just copied it from the original website :)

@senait ,,, no i didn't copy the exact sizes from HYF webiste in this last PR, but I don't remember if I did that when I pushed the 1st PR few days ago
although I still see conflicts so I'll try to resolve them

**Comment by Moamin-AbuEwaida** [comment]
oooh yeah, the conflicts are from the new part daniel pushed :+1:

**Comment by danielhalasz** [comment]
@Moamin-AbuEwaida you are using monospace, instead of "Space Mono" as the font, is that intentional?

**Comment by Moamin-AbuEwaida** [comment]
> Space Mono

Not really @danielhalasz , it might be a mistaken typo or sth

**Comment by Senait-coding** [comment]
@Moamin-AbuEwaida  I resolve the conflict this morning , and you did resolve it after and now again there is conflicts  :),  I will check it after I finish my part , or if other team members got time sure they will handle it .

**Comment by danielhalasz** [comment]
@Senait-coding I have modified a few things, fixed the conflicts, fixed the font and removed the uppercases

**Review by danielhalasz — APPROVED** [review]

**Review by Senait-coding — APPROVED** [review]

**Pull request merged**
