### PR TITLE
updated schedule table to row format // please fill in

### PR DESCRIPTION
**Pull request by danielhalasz**

### CODE REVIEW

**Review by bringmetheaxx — APPROVED** [review]
Fine

**Review by bringmetheaxx — APPROVED** [review]
add mine

**Review by bringmetheaxx — APPROVED** [review]

**Review by danielhalasz — COMMENTED** [review]
amazing

**Review by Senait-coding — APPROVED** [review]

**Comment by danielhalasz** [comment]
🎉

**Pull request merged**
