### PR TITLE
Section7 content

### PR DESCRIPTION
**Pull request by Moamin-AbuEwaida**
I've creating section 7 content part for review

### CODE REVIEW

**Comment by danielhalasz** [comment]
@Moamin-AbuEwaida can you please resolve the "conflicts"? thx

**Comment by Moamin-AbuEwaida** [comment]
> @Moamin-AbuEwaida can you please resolve the "conflicts"? thx

I'll do that and notify you @danielhalasz

**Comment by Moamin-AbuEwaida** [comment]
it's resolved, could you give it a look @danielhalasz ??

**Review by danielhalasz — APPROVED** [review]
LGTM, perfect

**Comment by bringmetheaxx** [comment]
There are some conflicts.

**Comment by danielhalasz** [comment]
probably another PR was approved since, so it has to be resolved again 😄

**Comment by Moamin-AbuEwaida** [comment]
I pushed an update which is not in the correct branch
I'll try to undo it and check the conflicts for the last review

**Comment by Moamin-AbuEwaida** [comment]
conflicts were resolved @bringmetheaxx

**Review by bringmetheaxx — APPROVED** [review]
great!

**Pull request merged**
