### PR TITLE
backlog 1 version

### PR DESCRIPTION
**Pull request by TatsianaRud**
can someone give me some advices?Thanks allot)

### CODE REVIEW

**Comment by TatsianaRud** [comment]
i m trying to communicate in github)

**Comment by Moamin-AbuEwaida** [comment]
Thanks for working on the document, looks good :grin: 
let's practice the communication about a certain topic or sth related to a PR in the same PR
I have 1 question, why are you using html tags rather than md tags?

**Comment by TatsianaRud** [comment]
I dont know how to change that in markdown,and now i dont know how to speak concreat to u,cos here i think i send message to everyone

**Review by lauraramirez220612 — COMMENTED** [review]
Good job Tatsiana.  For me it is ok.👍

**Comment by Moamin-AbuEwaida** [comment]
here we keep common conversation on the PR generally. and yes for sure we can have separate one-to-one conversations on slack
for the markdown  is just the simple tags we use such as # for the headers etc. etc. etc.

**Comment by TatsianaRud** [comment]
Can someone help me how to call this part

**Comment by Moamin-AbuEwaida** [comment]
> Can someone help me how to call this part
> 1dont know how to name it (OUR IMPACT)
> 2dont know how to name it (Our core values)

As I understood, you can call it "section"

**Review by bringmetheaxx — COMMENTED** [review]
for me it's looks fine, but I think it would be better if formatted as a .md file

**Review by Moamin-AbuEwaida — APPROVED** [review]
LGTM 
Thanks for working on the file

**Review by Senait-coding — APPROVED** [review]

**Pull request merged**
